#!/bin/bash

printf "Hello, Drip!\n"
printf "Ratios are expressed in:        coffee:water\n"
printf "For a light strength cup of coffe:   1:18\n"
printf "For a medium stregnth cup of coffe:  1:16\n"
printf "For a bold strength cup of coffe:    1:14\n"
